apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      containers:
        - name: tasks
          image: vishnu420/kub-network:tasks-api2
          env:
            - name: AUTH_ADDRESS
              # value: 10.109.23.176   
              value: auth-service.default
            - name: TASKS_FOLDER
              value: tasks